const productos = {
    list: [
        {
            id: 0,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 1,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 2,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 3,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 4,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 5,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 6,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 7,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        },
        {
            id: 8,
            name: "pitbull",
            imagen: "/stylesheets/imagenes/products/default-image.png",
            comentario: ["Texto del comentario que escribió el usuario Lorem ipsum dolor sit amet consectetur."],
            descripcion: ["Descripción corta del producto. En la página principal solo se ven 2 líneas de estar descripción.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tae ipsam amet eum, totam dolore libero illo unde? Consectetur dolorem neque veritatis."],
            descripcioncorta: ["Lorem ipsum dolor, sit amet consectetur adipisicing elit."],
        }
    ]
}